-- begin CUBA_SESSION
alter table CUBA_SESSION add constraint FK_CUBA_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references CUBA_SPEAKER(ID)^
create index IDX_CUBA_SESSION_ON_SPEAKER on CUBA_SESSION (SPEAKER_ID)^
-- end CUBA_SESSION
-- begin CUBA_SPEAKER
create unique index IDX_CUBA_SPEAKER_UNIQ_EMAIL on CUBA_SPEAKER (EMAIL) ^
create index IDX_CUBA_SPEAKER_LAST_NAME on CUBA_SPEAKER (LAST_NAME) ^
-- end CUBA_SPEAKER
